project_id: '591105'
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /blog/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-blog/**/%original_file_name%
  - source: /i18n/zh-cn/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /src/pages/**
    translation: i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
preserve_hierarchy: 1
